platform :ios,’7.0’
use_frameworks!
target 'IceKuangjia’ do
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'Masonry'
pod 'MJRefresh'
#pod 'IQKeyboardManager'
pod 'YYKit'
pod 'MJExtension'
end

